program: posterior_sample.py
method: bayes
metric:
  goal: maximize
  name: psnr_all

parameters:
  task.sd.mcmc_sampler_config.num_steps:
    min: 10
    max: 100

  task.sd.mcmc_sampler_config.lr:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-3

  task.sd.mcmc_sampler_config.momentum:
    min: 0.0
    max: 1.0
  
  task.sd.mcmc_sampler_config.lr_min_ratio:
    distribution: log_uniform_values
    min: 0.01
    max: 1.0

command:
  - ${env}
  - python
  - ${program}
  - +data=demo-ffhq
  - +model=stable-diffusion-v1.5
  - +task=phase_retrieval
  - num_runs=4
  - +sampler=sd_edm_daps
  - task_group=sd
  - save_dir=results/sweep
  - batch_size=10
  - data.start_id=0
  - data.end_id=10
  - gpu=0
  - name=sweep
  - model.prompt="a natural looking human face."
  - wandb=True
  - ${args_no_hyphens}

# ==============================
# K2/DA-HMC configs (skeleton)
# ==============================
k2_scheduler:
  name: k2
  target_cess: 0.85
  ksd_kernel: rbf
  ksd_bandwidth: median
  nonmonotone_reheat: true
  max_step_factor: 3.0

da_hmc:
  step_size_init: 0.01
  leapfrog: 6
  acc_target: 0.651
  surrogate:
    downsample: 2
    score_skip: true
  